# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sysl < Formula
  desc "Sysl generates code and documentation from system specifications"
  homepage "https://sysl.io/"
  version "0.718.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/anz-bank/sysl/releases/download/v0.718.0/sysl_0.718.0_darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "56b39fa85e305e3067c1bdd99c08f739ac0272bab2b3ba9c5d0c92e4b9e4de5f"

      def install
        bin.install "sysl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/anz-bank/sysl/releases/download/v0.718.0/sysl_0.718.0_darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "4299a4a4724779b7235b27a493ecfdb882b89afe6fc8ae09c3c2c16c172d72fe"

      def install
        bin.install "sysl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anz-bank/sysl/releases/download/v0.718.0/sysl_0.718.0_linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "505c860f98a4a8b9c5a647fe6cd4e079eb454b2d1d3e29c2c46d15acd4ca0401"

      def install
        bin.install "sysl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/anz-bank/sysl/releases/download/v0.718.0/sysl_0.718.0_linux-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "2e3ebe9cc3cd72d708ec6cd4cd04b7a491936f36c8c46c803999402155ee1d0a"

      def install
        bin.install "sysl"
      end
    end
  end

  test do
    system "#{bin}/sysl --version"
  end
end
