# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sysl < Formula
  desc "Sysl generates code and documentation from system specifications"
  homepage "https://sysl.io/"
  version "0.674.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/anz-bank/sysl/releases/download/v0.674.0/sysl_0.674.0_darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "87904a083cd7ccbdc43713e48cacb77d6ed3b6a9573845df67e5530aebbf338f"

      def install
        bin.install "sysl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/anz-bank/sysl/releases/download/v0.674.0/sysl_0.674.0_darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "74edb0f740d3cb0e047a192b964a570e70372cfbf96200b25e1953671406837c"

      def install
        bin.install "sysl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/anz-bank/sysl/releases/download/v0.674.0/sysl_0.674.0_linux-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "39cfe310b840127977164d45a234a6280dc378940cbf8f2f939e89a4de18b4e5"

      def install
        bin.install "sysl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anz-bank/sysl/releases/download/v0.674.0/sysl_0.674.0_linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0d4205c559869396eb3b04ec7819b8a09acbd041b12470abd541eb2e7a797998"

      def install
        bin.install "sysl"
      end
    end
  end

  test do
    system "#{bin}/sysl --version"
  end
end
