# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sysl < Formula
  desc "Sysl generates code and documentation from system specifications"
  homepage "https://sysl.io/"
  version "0.632.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/anz-bank/sysl/releases/download/v0.632.0/sysl_0.632.0_darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e3f61515728c7a087ee0bd67059d69a735090aa3561e2b5127707b45b60a44bd"

      def install
        bin.install "sysl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/anz-bank/sysl/releases/download/v0.632.0/sysl_0.632.0_darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "7e4ddbebff01cc74f2ae3e3d956581a9816bdf3521079a2b94ef016b1905d39f"

      def install
        bin.install "sysl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/anz-bank/sysl/releases/download/v0.632.0/sysl_0.632.0_linux-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "11a098d726c2d95efeccce36393f3c3a24e8e661f583bca41da42bfa2ecedceb"

      def install
        bin.install "sysl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anz-bank/sysl/releases/download/v0.632.0/sysl_0.632.0_linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b76f1ae847d80d9b81a12258633afa0e57d0861d8837555e5a964b92fc452a42"

      def install
        bin.install "sysl"
      end
    end
  end

  test do
    system "#{bin}/sysl --version"
  end
end
